name: 'first_job'

on:
  push:
    branches:
     - "main"
    paths:
     - 'api_1/**'
     - 'api_2/**'
    
  
  

jobs:
  Cloud_Resources_Deployment:
    name: 'Cloud_Resources_Deployment'
    runs-on: ubuntu-latest
    environment: production


    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Detect_Chnages
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          api_1_function_1:
            - 'api_1/function_1/**'
          api_1_function_2:
            - 'api_1/function_2/**'
          api_2_function_1:
            - 'api_2/function_1/**'
          api_2_function_2:
            - 'api_2/function_2/**'

    - name: Setup_Terraform
      uses: hashicorp/setup-terraform@v1

    - name: api_1_function_1
      if: steps.changes.outputs.api_1_function_1 == 'true' 
      run: |
           bash play.sh "api_1/function_1/terraform"
    
      env:
         CREDENTIALS : ${{ secrets.TF_API_TOKEN }}


    - name: api_1_function_2
      if: steps.changes.outputs.api_1_function_2 == 'true' 
      run: |
          bash play.sh "api_1/function_2/terraform"

      env:
         CREDENTIALS : ${{ secrets.TF_API_TOKEN }}


    - name: api_2_function_1
      if: steps.changes.outputs.api_2_function_1 == 'true' 
      run: |
           bash play.sh "api_2/function_1/terraform"
      env:
         CREDENTIALS : ${{ secrets.TF_API_TOKEN }}

    - name: api_2_function_2
      if: steps.changes.outputs.api_2_function_2 == 'true' 
      run: |
           bash play.sh "api_2/function_2/terraform"
      env:
         CREDENTIALS : ${{ secrets.TF_API_TOKEN }}

         

    
  

