name: 'first_job'

on:
  push:
    branches:
     - "main"
    paths:
     - 'eodhd_api/**'
    
  
  

jobs:
  first_job:
    name: 'testing_git_action'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'eodhd_api/eodhd_bulk_prices/cloudfunction/**'
          infra:
            - 'eodhd_api/eodhd_bulk_prices/terraform/**'
                      
    - name: cloudfunction deploy
      if: steps.changes.outputs.src == 'true'
      run: echo "changes in cloud function path"
      
    - name: terraform deploy
      if: steps.changes.outputs.infra == 'true'
      run: |
         ls
         echo "chnages in terraform path"
    
  

